# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84cab7fec254b9248d2325df52b5158c9c5ae9b9e12874c67672f46e9e340b048a86a09c26005dbd1e185e36046d944ede9a3a0e5e135eff05097cccc6f3d515

test:
  secret_key_base: 69069d2cd365c32e2696982e5f24cbb62d3585025764229fd5c80ced4c6961b2e507d30053b87fc3dbd2a44593995d759250825e76d9f8e13ed65e320ff12902

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
